// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model.Entities;

namespace Model.Migrations
{
    [DbContext(typeof(EFCultuurhuisContext))]
    partial class EFCultuurhuisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Entities.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GenreNaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            GenreNaam = "Humor"
                        },
                        new
                        {
                            GenreId = 2,
                            GenreNaam = "Theater"
                        },
                        new
                        {
                            GenreId = 3,
                            GenreNaam = "Muziek"
                        },
                        new
                        {
                            GenreId = 4,
                            GenreNaam = "Wereldmuziek"
                        },
                        new
                        {
                            GenreId = 5,
                            GenreNaam = "Familie"
                        },
                        new
                        {
                            GenreId = 6,
                            GenreNaam = "Dans"
                        },
                        new
                        {
                            GenreId = 7,
                            GenreNaam = "Multimedia"
                        },
                        new
                        {
                            GenreId = 8,
                            GenreNaam = "Modern klassiek"
                        },
                        new
                        {
                            GenreId = 9,
                            GenreNaam = "Muziektheater"
                        },
                        new
                        {
                            GenreId = 10,
                            GenreNaam = "Circustheater"
                        });
                });

            modelBuilder.Entity("Model.Entities.Klant", b =>
                {
                    b.Property<int>("KlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FamilieNaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("GebruikersNaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Gemeente")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("HuisNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Paswoord")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Straat")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("VoorNaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("KlantId");

                    b.ToTable("Klanten");

                    b.HasData(
                        new
                        {
                            KlantId = 1,
                            FamilieNaam = "Desmet",
                            GebruikersNaam = "hans",
                            Gemeente = "Brussel",
                            HuisNr = "7",
                            Paswoord = "bolle",
                            PostCode = "1000",
                            Straat = "Keizerslaan",
                            VoorNaam = "Hans"
                        },
                        new
                        {
                            KlantId = 2,
                            FamilieNaam = "Blondeel",
                            GebruikersNaam = "alexandra",
                            Gemeente = "Brussel",
                            HuisNr = "65",
                            Paswoord = "belle",
                            PostCode = "1000",
                            Straat = "Anspachlaan",
                            VoorNaam = "Alexandra"
                        });
                });

            modelBuilder.Entity("Model.Entities.Reservatie", b =>
                {
                    b.Property<int>("ReservatieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KlantId")
                        .HasColumnType("int");

                    b.Property<short>("Plaatsen")
                        .HasColumnType("smallint");

                    b.Property<int>("VoorstellingsId")
                        .HasColumnType("int");

                    b.HasKey("ReservatieId");

                    b.HasIndex("KlantId");

                    b.HasIndex("VoorstellingsId");

                    b.ToTable("Reservaties");
                });

            modelBuilder.Entity("Model.Entities.Voorstelling", b =>
                {
                    b.Property<int>("VoorstellingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Uitvoerders")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<short>("VrijePlaatsen")
                        .HasColumnType("smallint");

                    b.HasKey("VoorstellingsId");

                    b.HasIndex("GenreId");

                    b.ToTable("Voorstellingen");

                    b.HasData(
                        new
                        {
                            VoorstellingsId = 1,
                            Datum = new DateTime(2020, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 1,
                            Prijs = 5.0000m,
                            Titel = "Rechtstreeks & integraal/Ka-Boom!",
                            Uitvoerders = "Neveneffecten / Alex Agnew",
                            VrijePlaatsen = (short)0
                        },
                        new
                        {
                            VoorstellingsId = 2,
                            Datum = new DateTime(2020, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 2,
                            Prijs = 7.0000m,
                            Titel = "De leeuw van Vlaanderen",
                            Uitvoerders = "Union Suspecte / Publiekstheater",
                            VrijePlaatsen = (short)141
                        },
                        new
                        {
                            VoorstellingsId = 3,
                            Datum = new DateTime(2020, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 4,
                            Prijs = 6.0000m,
                            Titel = "Ano Neko",
                            Uitvoerders = "Dobet Gnahoré",
                            VrijePlaatsen = (short)200
                        },
                        new
                        {
                            VoorstellingsId = 4,
                            Datum = new DateTime(2020, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 2,
                            Prijs = 7.500m,
                            Titel = "Professor Bernhardi",
                            Uitvoerders = "de Roovers",
                            VrijePlaatsen = (short)180
                        },
                        new
                        {
                            VoorstellingsId = 5,
                            Datum = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 2,
                            Prijs = 7.0000m,
                            Titel = "Ich bin wie du",
                            Uitvoerders = "het Toneelhuis",
                            VrijePlaatsen = (short)150
                        },
                        new
                        {
                            VoorstellingsId = 6,
                            Datum = new DateTime(2020, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 5,
                            Prijs = 6.0000m,
                            Titel = "Randschade",
                            Uitvoerders = "fABULEUS",
                            VrijePlaatsen = (short)199
                        },
                        new
                        {
                            VoorstellingsId = 7,
                            Datum = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 2,
                            Prijs = 7.0000m,
                            Titel = "Koning Lear",
                            Uitvoerders = "Tonic",
                            VrijePlaatsen = (short)170
                        },
                        new
                        {
                            VoorstellingsId = 8,
                            Datum = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 3,
                            Prijs = 5.0000m,
                            Titel = "Van alle landen thuis",
                            Uitvoerders = "Els Helewaut,D.Van Esbroeck & co",
                            VrijePlaatsen = (short)200
                        },
                        new
                        {
                            VoorstellingsId = 9,
                            Datum = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 6,
                            Prijs = 8.0000m,
                            Titel = "Ma - Earth",
                            Uitvoerders = "Akram Khan",
                            VrijePlaatsen = (short)180
                        },
                        new
                        {
                            VoorstellingsId = 10,
                            Datum = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 7,
                            Prijs = 7.5000m,
                            Titel = "Jerusalem",
                            Uitvoerders = "Berlin",
                            VrijePlaatsen = (short)198
                        },
                        new
                        {
                            VoorstellingsId = 11,
                            Datum = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 5,
                            Prijs = 4.0000m,
                            Titel = "De fijnste dagen van het jaar",
                            Uitvoerders = "Het Paleis/Jenny",
                            VrijePlaatsen = (short)168
                        },
                        new
                        {
                            VoorstellingsId = 12,
                            Datum = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 4,
                            Prijs = 6.0000m,
                            Titel = "Cancion de un amorio",
                            Uitvoerders = "Bodicxhel",
                            VrijePlaatsen = (short)200
                        },
                        new
                        {
                            VoorstellingsId = 13,
                            Datum = new DateTime(2020, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 1,
                            Prijs = 6.0000m,
                            Titel = "Moest ik van u zijn",
                            Uitvoerders = "Wouter Deprez",
                            VrijePlaatsen = (short)198
                        },
                        new
                        {
                            VoorstellingsId = 14,
                            Datum = new DateTime(2020, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 1,
                            Prijs = 6.5000m,
                            Titel = "Poézique cabaret",
                            Uitvoerders = "La du chien qui tousse",
                            VrijePlaatsen = (short)200
                        },
                        new
                        {
                            VoorstellingsId = 15,
                            Datum = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 2,
                            Prijs = 5.500m,
                            Titel = "Eekhoornbrood",
                            Uitvoerders = "Lampe",
                            VrijePlaatsen = (short)180
                        },
                        new
                        {
                            VoorstellingsId = 16,
                            Datum = new DateTime(2020, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 8,
                            Prijs = 8.0000m,
                            Titel = "Liederen v. Baert, Debussy, Chausson, Weill",
                            Uitvoerders = "Bernard Baert & Anna Pardon",
                            VrijePlaatsen = (short)198
                        },
                        new
                        {
                            VoorstellingsId = 17,
                            Datum = new DateTime(2020, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 2,
                            Prijs = 7.0000m,
                            Titel = "L'Hafa",
                            Uitvoerders = "Union Suspecte",
                            VrijePlaatsen = (short)200
                        },
                        new
                        {
                            VoorstellingsId = 18,
                            Datum = new DateTime(2020, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 3,
                            Prijs = 6.0000m,
                            Titel = "Achter 't eten",
                            Uitvoerders = "Ceremonia/Het muziek Lod / Theater Zuidpool",
                            VrijePlaatsen = (short)180
                        },
                        new
                        {
                            VoorstellingsId = 19,
                            Datum = new DateTime(2020, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 8,
                            Prijs = 8.0000m,
                            Titel = "Poulenc / Stravinsky",
                            Uitvoerders = "Prometheus Ensemble",
                            VrijePlaatsen = (short)200
                        },
                        new
                        {
                            VoorstellingsId = 20,
                            Datum = new DateTime(2020, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 4,
                            Prijs = 7.0000m,
                            Titel = "Lied der rusteloosheid",
                            Uitvoerders = "Eva De Roovere,Pedro Moutinho & G.de Mol",
                            VrijePlaatsen = (short)190
                        },
                        new
                        {
                            VoorstellingsId = 21,
                            Datum = new DateTime(2020, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 5,
                            Prijs = 5.0000m,
                            Titel = "Wilde dingen",
                            Uitvoerders = "Kopergietery",
                            VrijePlaatsen = (short)196
                        },
                        new
                        {
                            VoorstellingsId = 22,
                            Datum = new DateTime(2020, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 7,
                            Prijs = 6.0000m,
                            Titel = "Licht",
                            Uitvoerders = "Bos",
                            VrijePlaatsen = (short)94
                        },
                        new
                        {
                            VoorstellingsId = 23,
                            Datum = new DateTime(2020, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 5,
                            Prijs = 6.0000m,
                            Titel = "Een hond in de nacht",
                            Uitvoerders = "Speeltheater Holland",
                            VrijePlaatsen = (short)0
                        },
                        new
                        {
                            VoorstellingsId = 24,
                            Datum = new DateTime(2020, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 2,
                            Prijs = 7.0000m,
                            Titel = "Gloed",
                            Uitvoerders = "theater Malpertuis",
                            VrijePlaatsen = (short)196
                        },
                        new
                        {
                            VoorstellingsId = 25,
                            Datum = new DateTime(2020, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 8,
                            Prijs = 8.0000m,
                            Titel = "To speak or not to speak",
                            Uitvoerders = "Spectra Ensemble",
                            VrijePlaatsen = (short)200
                        },
                        new
                        {
                            VoorstellingsId = 26,
                            Datum = new DateTime(2020, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 4,
                            Prijs = 7.2500m,
                            Titel = "Tres cultures por la paz",
                            Uitvoerders = "Rosa Zaragoza",
                            VrijePlaatsen = (short)190
                        },
                        new
                        {
                            VoorstellingsId = 27,
                            Datum = new DateTime(2020, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 10,
                            Prijs = 5.0000m,
                            Titel = "Zouff!",
                            Uitvoerders = "Les Argonautes",
                            VrijePlaatsen = (short)200
                        },
                        new
                        {
                            VoorstellingsId = 28,
                            Datum = new DateTime(2020, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 10,
                            Prijs = 6.0000m,
                            Titel = "La cucina dell'arte",
                            Uitvoerders = "David & Danny Ronaldo",
                            VrijePlaatsen = (short)190
                        },
                        new
                        {
                            VoorstellingsId = 29,
                            Datum = new DateTime(2020, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 8,
                            Prijs = 8.0000m,
                            Titel = "Speelt Rzewski",
                            Uitvoerders = "Frederic Rzewski",
                            VrijePlaatsen = (short)160
                        },
                        new
                        {
                            VoorstellingsId = 30,
                            Datum = new DateTime(2020, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 3,
                            Prijs = 7.0000m,
                            Titel = "Tv-tunes K.N.T.",
                            Uitvoerders = "Wim Opbrouck & Maandacht",
                            VrijePlaatsen = (short)200
                        },
                        new
                        {
                            VoorstellingsId = 31,
                            Datum = new DateTime(2020, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 3,
                            Prijs = 6.0000m,
                            Titel = "Schone woorden klinken zo...",
                            Uitvoerders = "Warre Borgmans & Jokke Schreurs",
                            VrijePlaatsen = (short)180
                        },
                        new
                        {
                            VoorstellingsId = 32,
                            Datum = new DateTime(2020, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 3,
                            Prijs = 5.5000m,
                            Titel = "White Light White Heat - The Velvet Undergr.",
                            Uitvoerders = "Bea Van der Maat & Dr Kloot Per W",
                            VrijePlaatsen = (short)200
                        },
                        new
                        {
                            VoorstellingsId = 33,
                            Datum = new DateTime(2020, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 1,
                            Prijs = 6.0000m,
                            Titel = "Het gaat toch rap",
                            Uitvoerders = "Raf Coppens",
                            VrijePlaatsen = (short)170
                        },
                        new
                        {
                            VoorstellingsId = 34,
                            Datum = new DateTime(2020, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 2,
                            Prijs = 7.0000m,
                            Titel = "Emilia Galotti",
                            Uitvoerders = "Tijd",
                            VrijePlaatsen = (short)198
                        },
                        new
                        {
                            VoorstellingsId = 35,
                            Datum = new DateTime(2020, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 2,
                            Prijs = 6.0000m,
                            Titel = "Iets over de liefde",
                            Uitvoerders = "theater Malpertuis",
                            VrijePlaatsen = (short)160
                        },
                        new
                        {
                            VoorstellingsId = 36,
                            Datum = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 8,
                            Prijs = 7.0000m,
                            Titel = "Hendrickx, Xenakis & Tan Dun",
                            Uitvoerders = "Spiegel Strijkkwartet",
                            VrijePlaatsen = (short)180
                        },
                        new
                        {
                            VoorstellingsId = 37,
                            Datum = new DateTime(2020, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 3,
                            Prijs = 6.0000m,
                            Titel = "Cry like a man, part 2",
                            Uitvoerders = "J.Blaute,Paul Michiels & Roland",
                            VrijePlaatsen = (short)8
                        },
                        new
                        {
                            VoorstellingsId = 38,
                            Datum = new DateTime(2020, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GenreId = 2,
                            Prijs = 7.0000m,
                            Titel = "De Kreutzersonates",
                            Uitvoerders = "Het Net",
                            VrijePlaatsen = (short)100
                        });
                });

            modelBuilder.Entity("Model.Entities.Reservatie", b =>
                {
                    b.HasOne("Model.Entities.Klant", "Klant")
                        .WithMany("Reservaties")
                        .HasForeignKey("KlantId")
                        .HasConstraintName("FK_Reservatie_Klant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entities.Voorstelling", "Voorstelling")
                        .WithMany("Reservaties")
                        .HasForeignKey("VoorstellingsId")
                        .HasConstraintName("FK_Reservatie_Voorstelling")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Entities.Voorstelling", b =>
                {
                    b.HasOne("Model.Entities.Genre", "Genre")
                        .WithMany("Voorstellingen")
                        .HasForeignKey("GenreId")
                        .HasConstraintName("FK_Voorstelling_Genre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
